services:
  jenkins:
    restart: always
    image: ${JENKINS_IMAGE_NAME}:${JENKINS_IMAGE_TAG}
    container_name: ${JENKINS_CONTAINER_NAME}
    hostname: ${JENKINS_HOSTNAME}
    networks:
      frontend:
    ports:
      - "8080:8080/tcp"
      - "50000:${JENKINS_SLAVE_AGENT_PORT}/tcp"
    volumes:
      - "jenkins_home:/var/jenkins_home"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ## Uncomment in case you see the message "This Jenkins instance appears to be offline."
    #dns:
    #  - 1.1.1.1
    #  - 8.8.8.8
    environment:
      #- JENKINS_JAVA_OPTS=
      #- JAVA_OPTS=-Dhudson.footerURL=http://mycompany.com
      ## If this property is already set in JAVA_OPTS or JENKINS_JAVA_OPTS, then the value of JENKINS_SLAVE_AGENT_PORT will be ignored.
      ## This port set up only at first init!
      - JENKINS_SLAVE_AGENT_PORT=${JENKINS_SLAVE_AGENT_PORT}
      - TZ="Europe/Moscow"
    healthcheck:
      # Use ${JENKINS_SLAVE_AGENT_PORT} port for healthcheck because 8080 needs auth
      test: ["CMD", "curl", "-f", "http://0.0.0.0:${JENKINS_SLAVE_AGENT_PORT}"]
      start_period: 3m
      interval: 30s
      retries: 3
      timeout: 3s

  jenkins-ssh-agent:
    build:
      context: ./image/jenkins-ssh-agent
      dockerfile: Dockerfile
      args:
        - JENKINS_SSH_DOCKERHUB_IMAGE_NAME=${JENKINS_SSH_DOCKERHUB_IMAGE_NAME}
        - JENKINS_SSH_DOCKERHUB_IMAGE_TAG=${JENKINS_SSH_DOCKERHUB_IMAGE_TAG}
        - OPM_URL=${OPM_URL}
        # Locale
        - ENV_LANG=${ENV_LANG}
        - ENV_LC_ALL=${ENV_LC_ALL}
        - ENV_LOCALE_GEN=${ENV_LOCALE_GEN}
        - ENV_TZ=${ENV_TZ}
        # SonarScanner
        - SONAR_SCANNER_VERSION=${SONAR_SCANNER_VERSION}
        # VNC
        - VNC_DISPLAY=${JENKINS_SSH_VNC_DISPLAY}
        - VNC_RESOLUTION=${JENKINS_SSH_VNC_RESOLUTION}
        - VNC_USER=${JENKINS_SSH_VNC_USER}
      secrets:
        - VNC_PASSWORD
    restart: always
    image: ${JENKINS_SSH_IMAGE_NAME}:${JENKINS_SSH_IMAGE_TAG}
    ## Variant 2: Do not use Dockerfile for ssh keys from github to known_hosts
    # command: >
    #   bash -c "
    #   mkdir -p /home/jenkins/.ssh
    #   && ssh-keyscan -t ed25519 github.com >> /home/jenkins/.ssh/known_hosts
    #   && chown -R jenkins:jenkins /home/jenkins/.ssh
    #   && /usr/local/bin/setup-sshd"
    container_name: ${JENKINS_SSH_CONTAINER_NAME}
    hostname: ${JENKINS_SSH_HOSTNAME}
    networks:
      frontend:
    expose:
      - "22/tcp"
    ports:
    #   - "2200:22/tcp"
      - "7860:7860/tcp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    volumes:
      - jenkins-ssh-agent:/home/jenkins/agent:rw
      - jenkins-ssh-agent-downloads:/home/chromium/Downloads
      # for Allure reports export
      - "allure_projects:/app/projects"
    depends_on:
      jenkins:
        condition: service_healthy      
    healthcheck:
      test: "ss | grep :22 > /dev/null; if [ 0 != $? ]; then exit 1; fi;"
      start_period: 5s
      interval: 30s
      retries: 3
      timeout: 5s

  sc_sonarqube:
    image: ${SONAR_IMAGE_NAME}:${SONAR_IMAGE_TAG}
    container_name: ${SONAR_CONTAINER_NAME}
    hostname: ${SONAR_HOSTNAME}
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      sc_db:
        condition: service_healthy
    links:
      - sc_db:db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/${SONAR_POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${SONAR_POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${SONAR_POSTGRES_PASSWORD}
    volumes:
      - sc_sonarqube_conf:/opt/sonarqube/conf
      - sc_sonarqube_data:/opt/sonarqube/data
      - sc_sonarqube_logs:/opt/sonarqube/logs
      - sc_sonarqube_extensions:/opt/sonarqube/extensions
      - sc_sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      frontend:      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9000"]
      start_period: 1m
      interval: 30s
      retries: 3
      timeout: 3s

  sc_db:
    restart: always
    image: ${SONAR_POSTGRES_IMAGE_NAME}:${SONAR_POSTGRES_IMAGE_TAG}
    container_name: ${SONAR_POSTGRES_CONTAINER_NAME}
    hostname: ${SONAR_POSTGRES_HOSTNAME}
    expose:
      - "5432:5432"
    # ports:
    #   - "5432:5432"
    command: postgres -c 'max_connections=300'
    volumes:
      - sc_postgresql:/var/lib/postgresql
      - sc_postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SONAR_POSTGRES_DB}
      POSTGRES_USER: ${SONAR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SONAR_POSTGRES_PASSWORD}
    networks:
      frontend:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${SONAR_POSTGRES_DB} -U $${SONAR_POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  allure:
    restart: always
    image: "${ALLURE_API_IMAGE_NAME}:${ALLURE_API_IMAGE_TAG}"
    container_name: "${ALLURE_API_CONTAINER_NAME}"
    hostname: "${ALLURE_API_HOSTNAME}"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
      SECURITY_USER: ${ALLURE_API_SECURITY_USER}
      SECURITY_PASS: ${ALLURE_API_SECURITY_PASS}
      SECURITY_VIEWER_USER: ${ALLURE_API_SECURITY_VIEWER_USER}
      SECURITY_VIEWER_PASS: ${ALLURE_API_SECURITY_VIEWER_PASS}
      SECURITY_ENABLED: 1
      MAKE_VIEWER_ENDPOINTS_PUBLIC: 0
      ## CORS Chrome bug
      ALLURE_CORS_ENABLED: true
      ## 10 min
      ALLURE_CORS_MAX_AGE: 600
      ALLURE_CORS_ALLOWED_ORIGINS: 'http://host.docker.internal:5252'
      ALLURE_CORS_ALLOWED_HEADERS: 'x-xsrf-token,content-type,authorization,sec-ch-ua,sec-ch-ua-mobile,user-agent'
      ALLURE_CORS_ALLOWED_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
      ALLURE_CORS_ALLOW_CREDENTIALS: true
    ports:
      # could be accessed by: http://host.docker.internal:5050 or external hostname
      - "5050:5050"
    volumes:
      - "allure_projects:/app/projects"
    networks:
      frontend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5050"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  allure-ui:
    image: "${ALLURE_UI_IMAGE_NAME}:${ALLURE_UI_IMAGE_TAG}"
    container_name: "${ALLURE_UI_CONTAINER_NAME}"
    hostname: "${ALLURE_UI_HOSTNAME}"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://host.docker.internal:5050"
      ## Prefix for API
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
      ## Prefix for UI
      URL_PREFIX: ""
    depends_on:
      allure:
        condition: service_healthy
    ports:
      - "5252:5252"
    restart: always
    networks:
      frontend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5252"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  grafana:
    restart: always
    image: ${GRAFANA_IMAGE_NAME}:${GRAFANA_IMAGE_TAG}
    container_name: ${GRAFANA_CONTAINER_NAME}
    hostname: ${GRAFANA_HOSTNAME}
    networks:
      frontend:
    ports:
      - "3000:3000"
    environment:
#     - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_FEATURE_TOGGLES_ENABLE=${GF_FEATURE_TOGGLES_ENABLE}
      - GF_DEFAULT_INSTANCE_NAME=${GF_DEFAULT_INSTANCE_NAME}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      ## Set GF_SECURITY_ADMIN_PASSWORD if you need to set other password than admin/admin
      # - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      # predefine datasources
      - grafana-datasources:/etc/grafana/provisioning/datasources
      - grafana-dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
      - grafana-logs:/etc/grafana/logs
    command:
    #   - --config=/etc/grafana/grafana_custom.ini
      - cfg:default.paths.logs=/etc/grafana/logs
    depends_on:
      prometheus:
        condition: service_healthy
      ## Uncomment if use in Linux, comment winexporter below
      node-exporter:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3000"]
      start_period: 5s
      interval: 30s
      retries: 3
      timeout: 5s

  prometheus:
    restart: always
    image: ${PROMETHEUS_IMAGE_NAME}:${PROMETHEUS_IMAGE_TAG}
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    hostname: ${PROMETHEUS_HOSTNAME}
    networks:
      frontend:
    expose:
      - 9090
    # ports:
    #   - "9090:9090"
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
    healthcheck:
      test: "wget --no-verbose --tries=3 --spider http://0.0.0.0:9090/metrics || exit 1"
      start_period: 5s
      interval: 30s
      retries: 3
      timeout: 5s

  node-exporter:
    restart: always
    image: ${NODE_IMAGE_NAME}:${NODE_IMAGE_TAG}
    container_name: ${NODE_CONTAINER_NAME}
    hostname: ${NODE_HOSTNAME}
    networks:
      frontend:
    expose:
      - 9100
    # ports:
    #   - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    healthcheck:
      test: "wget --no-verbose --tries=3 --spider http://0.0.0.0:9100/metrics || exit 1"
      start_period: 5s
      interval: 30s
      retries: 3
      timeout: 5s

secrets:
  VNC_PASSWORD:
    environment: JENKINS_SSH_VNC_PASSWORD

networks:
  frontend:

volumes:

# --> Jenkins volumes  
  jenkins_home:
    driver: local
    driver_opts:
      type: none
      device: "./data/home"
      o: bind
# <-- Jenkins volumes

# --> Jenkins Agents volumes
  jenkins-ssh-agent:
    driver: local
    driver_opts:
      type: none
      device: "./data/ssh-agent"
      o: bind

  jenkins-ssh-agent-downloads:
    driver: local
    driver_opts:
      type: none
      device: "./data/ssh-agent-downloads"
      o: bind
# <-- Jenkins Agents volumes

# --> Sonarqube volumes
  sc_sonarqube_conf:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/sonarqube_conf"

  sc_sonarqube_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/sonarqube_data"

  sc_sonarqube_logs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/sonarqube_logs"

  sc_sonarqube_extensions:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/sonarqube_extensions"      

  sc_sonarqube_bundled-plugins:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/sonarqube_bundled_plugins"

  sc_postgresql:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/sc_postgresql"

  sc_postgresql_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/sc_postgresql_data"
# <-- Sonarqube volumes

# --> Allure volumes
  allure_projects:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/allure_projects"
# <-- Allure volumes

# --> Grafana volumes
  grafana-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/grafana/data"

  grafana-logs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/grafana/logs"
  
  grafana-datasources:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/grafana/datasources"

  grafana-dashboards:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/grafana/dashboards"
# <-- Grafana volumes

# --> Prometheus volumes
  prom-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/prometheus/data"

  prom-configs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/prometheus/configs"
# <-- Prometheus volumes